/**
 * Generate real sample data for docs.
 *
 * Runs the full VP flow with real ZKP proofs and writes JSON files.
 * This is NOT a mock — every proof is generated by real circuits.
 *
 * Run: npx vitest run __tests__/generate-sample-data.test.ts
 */

import { describe, it, beforeAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import { VPRequestBuilder } from '../src/builder/request-builder.js';
import { DocumentRequestBuilder } from '../src/builder/document-request-builder.js';
import { matchCredentials } from '../src/resolver/matcher.js';
import { resolvePresentation } from '../src/resolver/resolver.js';
import { createICAO9303ProofSystem } from '../src/proof-system/icao9303-proof-system.js';
import { createWasmZKPProvider, createPoseidon2Hasher, buildMerkleTree } from '@1matrix/zkp-provider';
import type { ZKPProvider, Poseidon2Hasher } from '@1matrix/zkp-provider';
import type { SchemaProofSystem } from '../src/types/proof-system.js';
import { motherCCCD } from './fixtures/cccd-factory.js';

const DOCS_DIR = path.resolve(__dirname, '../../../docs/samples');

let zkpProvider: ZKPProvider & { destroy(): void };
let poseidon2: Poseidon2Hasher;
let proofSystem: SchemaProofSystem;

beforeAll(async () => {
  poseidon2 = await createPoseidon2Hasher();
  zkpProvider = await createWasmZKPProvider();
  proofSystem = createICAO9303ProofSystem({ poseidon2, buildMerkleTree });
  fs.mkdirSync(DOCS_DIR, { recursive: true });
}, 60000);

function writeJSON(filename: string, data: unknown) {
  fs.writeFileSync(path.join(DOCS_DIR, filename), JSON.stringify(data, null, 2) + '\n');
}

/** Truncate base64 proof values for readability, keep structure intact */
function truncateProofs(obj: unknown): unknown {
  if (typeof obj === 'string' && obj.length > 120 && /^[A-Za-z0-9+/=]+$/.test(obj)) {
    return obj.slice(0, 40) + '...[' + obj.length + ' chars total]';
  }
  if (Array.isArray(obj)) return obj.map(truncateProofs);
  if (obj && typeof obj === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      out[k] = truncateProofs(v);
    }
    return out;
  }
  return obj;
}

describe('Generate sample data', () => {
  it('generates VP request + response with real ZKP proofs', async () => {
    const cccd = motherCCCD;

    // ── Scenario 1: Bank KYC — disclose fullName + gender ──

    const request = new VPRequestBuilder('kyc-001', 'nonce-abc123')
      .setName('Bank KYC Verification')
      .setVerifier({ id: 'did:web:bank.vn', name: 'Vietnam International Bank', url: 'https://bank.vn' })
      .setExpiresAt('2099-12-31T23:59:59Z')
      .addDocumentRequest(
        new DocumentRequestBuilder('cccd', 'CCCDCredential')
          .setSchemaType('ICAO9303SOD')
          .setName('National ID (CCCD)')
          .disclose({ field: 'fullName' })
          .disclose({ field: 'gender' }),
      )
      .build();

    writeJSON('vp-request.json', request);

    // ── Scenario 2: Request with predicates ──

    const requestWithPredicates = new VPRequestBuilder('enroll-001', 'nonce-xyz789')
      .setName('School Enrollment Check')
      .setVerifier({ id: 'did:web:school.edu.vn', name: 'HCMC University', url: 'https://school.edu.vn' })
      .setExpiresAt('2099-12-31T23:59:59Z')
      .addDocumentRequest(
        new DocumentRequestBuilder('student-cccd', 'CCCDCredential')
          .setSchemaType('ICAO9303SOD')
          .setName('Student National ID')
          .disclose({ field: 'fullName' })
          .inRange({ field: 'dateOfBirth', gte: '19900101', lte: '20061231' })
          .greaterThanOrEqual({ field: 'dateOfBirth', value: '19900101', id: 'dob-gte' }),
      )
      .addDocumentRequest(
        new DocumentRequestBuilder('parent-cccd', 'CCCDCredential')
          .setSchemaType('ICAO9303SOD')
          .setName('Parent National ID')
          .disclose({ field: 'fullName' })
          .equals({ field: 'fullName', ref: 'student-cccd.fatherName', id: 'parent-match' }),
      )
      .build();

    writeJSON('vp-request-with-predicates.json', requestWithPredicates);

    // ── Resolve VP with real ZKP proofs ──

    const matchResult = matchCredentials(
      request.rules,
      [cccd.credential],
      { 'ICAO9303SOD': proofSystem },
    );

    const vp = await resolvePresentation(
      request,
      [cccd.credential],
      [{ docRequestID: 'cccd', credentialIndex: 0 }],
      {
        holder: 'did:key:z6MkHolder123',
        zkpProvider,
        proofSystems: { 'ICAO9303SOD': proofSystem },
        credentialData: () => ({
          sodInputs: cccd.sodInputs,
          dg13Inputs: cccd.dg13CircuitInputs,
          salt: cccd.salt,
          dscCertificate: cccd.dscCertificate,
        }),
        signPresentation: async () => ({
          type: 'DataIntegrityProof',
          verificationMethod: 'did:key:z6MkHolder123#keys-1',
          proofPurpose: 'authentication' as const,
          challenge: 'nonce-abc123',
          domain: 'bank.vn',
          proofValue: 'z' + 'A'.repeat(85),
        }),
      },
    );

    // Full VP (proof values are real but long)
    writeJSON('vp-response-full.json', vp);

    // Truncated VP (readable — proof values shortened)
    writeJSON('vp-response.json', truncateProofs(vp));

    // Matching result
    writeJSON('matching-result.json', matchResult);

    console.log(`\n✅ Sample data written to ${DOCS_DIR}/`);
    console.log('   - vp-request.json');
    console.log('   - vp-request-with-predicates.json');
    console.log('   - vp-response.json (truncated proofs)');
    console.log('   - vp-response-full.json (full proofs)');
    console.log('   - matching-result.json');
  }, 600000);
});
