/**
 * Codegen: reads VK constants from a TS source file (e.g. backend's vks.ts)
 * and emits `contracts/NationalIDRegistryVKs.sol` — three internal pure
 * functions returning the VerificationKey struct literals plus their hashes.
 *
 * Inlining VKs in bytecode avoids ~85k gas/tx of calldata and ~360k gas/tx of
 * SLOAD vs storing them in state. The cost is one-time deploy bytecode growth
 * of ~5.4 KB (well under EIP-170 limit for this registry).
 *
 * Usage:
 *   npx ts-node scripts/generate-vks-sol.ts <path-to-vks.ts>
 * Defaults to the backend copy at events-backend/.../registry/vks.ts.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

interface G1Point { x: string; y: string; }
interface VK {
  circuitSize: bigint;
  logCircuitSize: bigint;
  publicInputsSize: bigint;
  [k: string]: bigint | G1Point;
}

const FIELD_ORDER: readonly string[] = [
  'circuitSize', 'logCircuitSize', 'publicInputsSize',
  'qm', 'qc', 'ql', 'qr', 'qo', 'q4',
  'qLookup', 'qArith', 'qDeltaRange', 'qMemory', 'qNnf', 'qElliptic',
  'qPoseidon2External', 'qPoseidon2Internal',
  's1', 's2', 's3', 's4',
  'id1', 'id2', 'id3', 'id4',
  't1', 't2', 't3', 't4',
  'lagrangeFirst', 'lagrangeLast',
];

function loadVks(tsPath: string): { sod: VK; dgBridge: VK; uniqueId: VK; hashes: Record<string, string> } {
  // Import the TS file dynamically. Uses ts-node register when run via `npx ts-node`.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require(tsPath);
  return {
    sod: mod.sodValidateVk,
    dgBridge: mod.dgBridgeVk,
    uniqueId: mod.uniqueIdentityVk,
    hashes: {
      sod: mod.sodValidateVkHash,
      dgBridge: mod.dgBridgeVkHash,
      uniqueId: mod.uniqueIdentityVkHash,
    },
  };
}

function emitVK(name: string, vk: VK): string {
  const lines: string[] = [];
  lines.push(`    function _${name}Vk() internal pure returns (Honk.VerificationKey memory vk) {`);
  for (const field of FIELD_ORDER) {
    const v = vk[field];
    if (typeof v === 'bigint') {
      lines.push(`        vk.${field} = ${v.toString()};`);
    } else if (v && typeof v === 'object' && 'x' in v) {
      lines.push(`        vk.${field} = Honk.G1Point({ x: ${v.x}, y: ${v.y} });`);
    } else {
      throw new Error(`Missing/invalid field ${field} on ${name}`);
    }
  }
  lines.push(`    }`);
  return lines.join('\n');
}

function main() {
  const defaultSource = resolve(
    __dirname, '..', '..', '..', '..', '..', '..',
    'events-backend/apps/api/src/modules/registry/vks.ts',
  );
  const source = process.argv[2] ? resolve(process.argv[2]) : defaultSource;
  const outPath = resolve(__dirname, '..', 'contracts', 'NationalIDRegistryVKs.sol');

  const { sod, dgBridge, uniqueId, hashes } = loadVks(source);

  const body = [
    '// SPDX-License-Identifier: MIT',
    '// Auto-generated by scripts/generate-vks-sol.ts — DO NOT EDIT.',
    `// Source: ${source.replace(process.cwd(), '.')}`,
    'pragma solidity ^0.8.27;',
    '',
    'import {Honk} from "./interfaces/IUniversalHonkVerifier.sol";',
    '',
    'abstract contract NationalIDRegistryVKs {',
    `    uint256 internal constant SOD_VK_HASH = uint256(${hashes.sod});`,
    `    uint256 internal constant DG_BRIDGE_VK_HASH = uint256(${hashes.dgBridge});`,
    `    uint256 internal constant UNIQUE_ID_VK_HASH = uint256(${hashes.uniqueId});`,
    '',
    emitVK('sod', sod),
    '',
    emitVK('dgBridge', dgBridge),
    '',
    emitVK('uniqueId', uniqueId),
    '}',
    '',
  ].join('\n');

  writeFileSync(outPath, body);
  console.log(`Wrote ${outPath}`);
}

main();
